<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiveViewEngine.Poc.Shared\LiveViewEngine.Poc.Shared.csproj" />
        <ProjectReference Include="..\..\LiveViewEngine.TcpClient\LiveViewEngine.TcpClient.csproj" />
    </ItemGroup>
</Project>
